### PR TITLE
Show DOI

### PR DESCRIPTION
**Pull request by koppor**

### CODE REVIEW

**Comment by csware** [comment]
Is there a reason why DOI is disabled again in 022dca963afdaec52f65bfe9bd511b432e6fa94a?

**Comment by csware** [comment]
This should be configurable, at best via an option in the lni class.

**Comment by sieversMartin** [comment]
Well, we needed a quick solution and decided to suppress the output at all. Not the best solution in general I agree.

**Comment by sieversMartin** [comment]
If `doi` is set to `true` it should be output in front of the year, otherwise (and that may be the default) it will be suppressed as currently.

**Pull request merged**
